kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value: {}
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value: {}
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 700Mi
    target:
      kind: Deployment
      name: release-name-example-application
