---
# Source: example-application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-example-application
  labels:
    helm.sh/chart: example-application-0.1.0
    app.kubernetes.io/name: example-application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: example-application
    app.kubernetes.io/instance: release-name
---
# Source: example-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-example-application
  labels:
    helm.sh/chart: example-application-0.1.0
    app.kubernetes.io/name: example-application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-application
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-application
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: example-application
          securityContext:
            {}
          image: "quay.io/tosmi/nginx-unprivileged:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: example-application/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-example-application-test-connection"
  labels:
    helm.sh/chart: example-application-0.1.0
    app.kubernetes.io/name: example-application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: quay.io/tosmi/ubi9-utils:latest
      command: ['curl']
      args: ['-v', 'release-name-example-application:8080']
  restartPolicy: Never
