---
apiVersion: v1
kind: Service
metadata:
  name: release-name-example-application
  labels:
    helm.sh/chart: example-application-0.1.0
    app.kubernetes.io/name: example-application
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: example-application
    app.kubernetes.io/instance: release-name
